### ISSUE TITLE
Problem with TIMESTAMP 

### ISSUE THREAD

**Issue by sowe** [pentaho/pentaho-vertica-bulkloader#34]
Hi, 
We have a problem with this step , in particular with a timestamp. Was committed in this l[ink](http://jira.pentaho.com/browse/PDI-11958).
Any update?

**Comment by pamval** [comment]
No updates here. If you are a Pentaho customer, you can raise the priority by opening a support case or escalating with your CSM. 

Otherwise make sure you vote in the issue so that its visibility is raised.

thanks!

**Comment by sowe** [comment]
Hi Pedro,
I think I did not explain well. I cloned this report and I created this step however i have the same error with a timestamp. The link is only a example for the same behaviors.
I'm trying to debug and fix it but i cant ...

**Comment by pamval** [comment]
use the pentaho forums or the community mailing list. The links are here: http://community.pentaho.com/.

I think that's the fastest way to get help on debugging and generally working with the platform.

thanks!
